# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('orden', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('color', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Amarillo'), (3, 'Rojo'), (4, 'Morado'), (5, 'Azul')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('edad_ini', models.IntegerField(blank=True, null=True)),
                ('edad_fin', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=40, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('elemento_clave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_aprendizaje', to='programas.ElementoClave')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalidad', models.CharField(blank=True, max_length=10, null=True)),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='personalidades/')),
                ('elemento_clave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalidades', to='programas.ElementoClave')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacionimplementacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('programa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='programas.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=20, null=True)),
                ('elemento_clave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ElementoClave')),
            ],
        ),
        migrations.AddField(
            model_name='elementoclave',
            name='programa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementos_clave', to='programas.Programa'),
        ),
        migrations.AddField(
            model_name='casa',
            name='mundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='programas.ElementoClave'),
        ),
    ]
