# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(blank=True, max_length=30, unique=True)),
                ('pic_profile', models.ImageField(blank=True, default='ImagesProfile/people.png', null=True, upload_to='ImagesProfile', verbose_name='Imagen de perfil')),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador_master'), (2, 'Facilitador'), (3, 'Co_Facilitador')], default=1, null=True)),
                ('cambio_password', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('premio', models.IntegerField(blank=True, null=True)),
                ('tiempo_esperado', models.TimeField(blank=True, null=True)),
                ('casa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='programas.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadNino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasaNino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='programas.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nino', models.IntegerField(blank=True)),
                ('personalidad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='programas.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoNino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ElementoClave')),
            ],
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_apadr', models.IntegerField(blank=True)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('latitud', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('longitud', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AA', 'Apadrinado y Activo'), ('AI', 'Apadrinado e Inactivo'), ('NA', 'Nunca ha sido apadrinado')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NinoClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('ahorro', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('nino', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Nino')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='elementonino',
            name='nino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Nino'),
        ),
        migrations.AddField(
            model_name='casanino',
            name='nino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Nino'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='compra',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Compra'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='nino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Nino'),
        ),
        migrations.AddField(
            model_name='actividadnino',
            name='nino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Nino'),
        ),
    ]
