# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoclub',
            name='mundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ElementoClave'),
        ),
        migrations.AddField(
            model_name='cofre',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
        ),
        migrations.AddField(
            model_name='clubcita',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Cita'),
        ),
        migrations.AddField(
            model_name='clubcita',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
        ),
        migrations.AddField(
            model_name='club',
            name='programa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='programas.Programa'),
        ),
    ]
